# Generated by Django 5.2.6 on 2025-10-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='YYYY/MM/DD', null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='national_id',
            field=models.IntegerField(blank=True, help_text='2580945710', null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(blank=True, help_text='+989', null=True),
        ),
    ]
