# Generated by Django 5.2.6 on 2025-10-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usermodel_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='badge',
            field=models.CharField(blank=True, default='Beginner', max_length=50),
        ),
    ]
