# Generated by Django 5.2.5 on 2025-10-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usermodel_badge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='custom_id',
            new_name='user_custom_id',
        ),
    ]
